{
 "title": "Service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   { "name": "namespace", "query": "go_info" },
   { "name": "job", "query": "go_info" },
   { "name": "min_time_interval", "query": "2m" },
   { "name": "namespace_label", "query": "namespace" },
   { "name": "job_label", "query": "job" },
   { "name": "database_label", "query": "database" },
   { "name": "database", "query": "pace_postgres_query_total" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Number of HTTP requests within the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(pace_http_request_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Number of HTTP requests per second, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(pace_http_request_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Process",
   "type": "singlestat",
   "description": "Total RAM usage, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(go_goroutines{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"})"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "singlestat",
   "description": "Time in which 95% of all Postgres queries are processed, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pace_postgres_query_duration_seconds_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Number of HTTP requests that return 4xx and 5xx errors within the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(pace_http_request_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",code=~\"^[45][0-9]{2}$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Percentage of HTTP requests that return 4xx and 5xx errors, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(pace_http_request_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",code=~\"^[45][0-9]{2}$\"}[$__interval])) / sum(rate(pace_http_request_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Process",
   "type": "singlestat",
   "description": "Total RAM usage, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"})"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "singlestat",
   "description": "Time in which 95% of all Redis queries are processed, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pace_redis_cmd_duration_seconds_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "singlestat",
   "description": "Time in which 95% of all HTTP requests are served, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pace_http_request_duration_milliseconds_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "singlestat",
   "description": "Number of panics within the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(pace_http_panic_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Process",
   "type": "singlestat",
   "description": "Total RAM usage, averaged over the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(process_open_fds{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"})"
    }
   ]
  },
  {
   "title": "Livetests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pace_livetest_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"})"
    }
   ]
  },
  {
   "title": "Circuit Breakers",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(pace_http_circuit_breaker_state_switch_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",from=\"closed\"}[$__interval]) - ignoring(from, to) rate(pace_http_circuit_breaker_state_switch_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",to=\"closed\"}[$__interval])"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_api_http_request_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    },
    {
     "title": "Response Times",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(increase(pace_api_http_request_duration_seconds_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Sizes",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(increase(pace_api_http_size_bytes_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_http_request_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    },
    {
     "title": "Response Times",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "repeat": "database",
     "targets": [
      {
       "expr": "sum(increase(pace_http_request_duration_milliseconds_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Running Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pace_http_in_flight_requests{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"} - 1) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    },
    {
     "title": "Response Sizes",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(increase(pace_http_response_size_bytes_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "4xx Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_http_request_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",code=~\"^4[0-9]{2}$\"}[$__interval])) by (code, $job_label)",
       "legendFormat": "{{code}} ({{$job_label}})"
      }
     ]
    },
    {
     "title": "5xx Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_http_request_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",code=~\"^5[0-9]{2}$\"}[$__interval])) by (code, $job_label)",
       "legendFormat": "{{code}} ({{$job_label}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_virtual_memory_bytes{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_goroutines{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    },
    {
     "title": "Panics",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_http_panic_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_threads{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    },
    {
     "title": "Go Versions",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "max(go_info{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}) by ($job_label, version)"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_open_fds{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgres Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres Queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_query_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",$database_label=~\"^$database$\"}[$__interval])) by ($job_label,$database_label)",
       "legendFormat": "{{$database_label}} ({{$job_label}})"
      }
     ]
    },
    {
     "title": "Postgres Query Times",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(pace_postgres_query_duration_seconds_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",$database_label=~\"^$database$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Postgres Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_query_failed{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",$database_label=~\"^$database$\"}[$__interval])) by ($database_label, $job_label)",
       "legendFormat": "{{$database_label}} ({{$job_label}})"
      }
     ]
    },
    {
     "title": "Rows Returned",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_query_rows_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",$database_label=~\"^$database$\"}[$__interval])) by ($database_label, $job_label)",
       "legendFormat": "{{$database_label}} ({{$job_label}})"
      }
     ]
    },
    {
     "title": "Rows Affected",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_query_affected_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",$database_label=~\"^$database$\"}[$__interval])) by ($database_label, $job_label)",
       "legendFormat": "{{$database_label}} ({{$job_label}})"
      }
     ]
    },
    {
     "title": "Connection Pool Hits",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_connection_pool_hits{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\",$database_label=~\"^$database$\"}[$__interval])) by (pool, $database_label, $job_label)",
       "legendFormat": "{{pool}} ({{$database_label}}; {{$job_label}})"
      }
     ]
    },
    {
     "title": "Connection Pool Misses",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_connection_pool_misses{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (pool, $database_label, $job_label)",
       "legendFormat": "{{pool}} ({{$database_label}}; {{$job_label}})"
      }
     ]
    },
    {
     "title": "Connection Pool Timeouts",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_postgres_connection_pool_timeouts{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (pool, $database_label, $job_label)",
       "legendFormat": "{{pool}} ({{$database_label}}; {{$job_label}})"
      }
     ]
    },
    {
     "title": "Connection Pool Total Connections",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pace_postgres_connection_pool_total_conns{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}) by (pool, $database_label, $job_label)",
       "legendFormat": "{{pool}} ({{$database_label}}; {{$job_label}})"
      }
     ]
    },
    {
     "title": "Connection Pool Idle Connections",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pace_postgres_connection_pool_idle_conns{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}) by (pool, $database_label, $job_label)",
       "legendFormat": "{{pool}} ({{$database_label}}; {{$job_label}})"
      }
     ]
    },
    {
     "title": "Connection Pool Removed Stale Connections",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pace_postgres_connection_pool_stale_conns{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}) by (pool, $database_label, $job_label)",
       "legendFormat": "{{pool}} ({{$database_label}}; {{$job_label}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_redis_cmd_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    },
    {
     "title": "Redis Times",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(pace_redis_cmd_duration_seconds_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Redis Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_redis_cmd_failed{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Livetests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Livetests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_livetest_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval]) * 60) by (result)",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "sum(increase(pace_livetest_duration_seconds_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_objstore_req_total{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    },
    {
     "title": "Storage Times",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(increase(pace_objstore_req_duration_seconds_bucket{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Storage Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pace_objstore_req_failed{$namespace_label=~\"^$namespace$\",$job_label=~\"^$job$\"}[$__interval])) by ($job_label)",
       "legendFormat": "{{$job_label}}"
      }
     ]
    }
   ]
  }
 ]
}