{
  "openapi": "3.0.0",
  "info": {
    "title": "PACE POI API",
    "description": "POI API",
    "version": "0.0.1",
    "x-logo": {
      "url": "https://developer.pace.car/images/logo_black.svg"
    }
  },
  "servers": [
    {
      "url": "https://api.pace.cloud/poi"
    }
  ],
  "paths": {
    "/beta/meta": {
      "get": {
        "tags": [
          "Metadata Filters"
        ],
        "operationId": "GetMetadataFilters",
        "security": [
          {
            "OAuth2": [
              "poi:gas-stations:read"
            ]
          },
          {
            "OIDC": [
              "poi:gas-stations:read"
            ]
          }
        ],
        "summary": "Query for filterable values inside a radius",
        "description": "Returns filterable values around the current location on the map, within a certain radius.\nFor the latitude and longitude values used in the request, returns the available and unavailable values for the following fields:\n\n  * brand\n\n  * payment methods\n\n  * amenities\n"
      }
    },
    "/beta/gas-stations": {
      "get": {
        "tags": [
          "Gas Stations"
        ],
        "operationId": "GetGasStations",
        "security": [
          {
            "OAuth2": [
              "poi:gas-stations:read",
              "poi:gas-stations.references:read"
            ]
          },
          {
            "OIDC": [
              "poi:gas-stations:read",
              "poi:gas-stations.references:read"
            ]
          }
        ],
        "summary": "Query for gas stations",
        "description": "There are two ways to search for gas stations in a geo location. You can use either one, or none, but not both ways.\n\nTo search inside a specific radius around a given longitude and latitude provide the following query parameters:\n\n* latitude\n* longitude\n* radius\n\nTo search inside a bounding box provide the following query parameter:\n\n* boundingBox\n"
      }
    },
    "/beta/gas-stations/{id}": {
      "get": {
        "tags": [
          "Gas Stations"
        ],
        "operationId": "GetGasStation",
        "security": [
          {
            "OAuth2": [
              "poi:gas-stations:read",
              "poi:gas-stations.references:read"
            ]
          },
          {
            "OIDC": [
              "poi:gas-stations:read",
              "poi:gas-stations.references:read"
            ]
          }
        ],
        "summary": "Get a specific gas station",
        "description": "Returns an individual gas station\n"
      }
    },
    "/beta/gas-stations/{id}/fueltype": {
      "get": {
        "tags": [
          "Gas Stations"
        ],
        "operationId": "GetGasStationFuelTypeNameMapping",
        "security": [
          {
            "OAuth2": [
              "poi:gas-stations:read"
            ]
          },
          {
            "OIDC": [
              "poi:gas-stations:read"
            ]
          }
        ],
        "summary": "Get a mapping from gas station specific fuel product name mapped to a normalized fuel type",
        "description": "Every gas station potential has different names for the same fuel types. This endpoint accepts the gas station's specific name and return a mapping where the specific name is mapped to a normalized version which should be globally the same across gas stations.\n"
      }
    },
    "/beta/gas-stations/{id}/fuel-price-histories/{fuel_type}": {
      "get": {
        "tags": [
          "Price Histories"
        ],
        "operationId": "GetPriceHistory",
        "security": [
          {
            "OAuth2": [
              "poi:gas-stations:read"
            ]
          }
        ],
        "summary": "Get price history for a specific gas station",
        "description": "Get the price history for a specific gas station and fuel type on a period of time which can begin no sooner than 37 days ago; the time interval between price changes can be set to minute, hour, day, week, month or year\n"
      }
    },
    "/beta/subscriptions": {
      "get": {
        "tags": [
          "Subscriptions"
        ],
        "operationId": "GetSubscriptions",
        "security": [
          {
            "OAuth2": [
              "poi:subscriptions:read"
            ]
          },
          {
            "OIDC": [
              "poi:subscriptions:read"
            ]
          },
          {
            "DeviceID": []
          }
        ],
        "summary": "Get the list of POI subscriptions for the user or device\n",
        "description": "Returns a list of all current (not expired) subscriptions of the user.\n"
      }
    },
    "/beta/subscriptions/{id}": {
      "put": {
        "tags": [
          "Subscriptions"
        ],
        "operationId": "StoreSubscription",
        "security": [
          {
            "OAuth2": [
              "poi:subscriptions:create"
            ]
          },
          {
            "OIDC": [
              "poi:subscriptions:create"
            ]
          },
          {
            "DeviceID": []
          }
        ],
        "summary": "Stores a POI subscription\n",
        "description": "Stores a POI subscription to send a push notification to the device with the specified `pushToken` once one of the pois change based on the change condition. The notification contains (max 4kb)\n```\n{\n  \"target\": \"...\"\n  \"subscription\": \"706087b4-8bca-4db9-b037-8a7ff4ce5633\",\n  \"poi\": {\n    \"id\": \"4d6dd9db-b0ac-40e8-a099-b606cace6f72\", # poi ID\n    \"type\": \"gasStation\",\n    \"attributes\": {\n      # ... more data of the type\n    }\n  }\n}\n```\n[...]"
      },
      "delete": {
        "tags": [
          "Subscriptions"
        ],
        "operationId": "DeleteSubscription",
        "security": [
          {
            "OAuth2": [
              "poi:subscriptions:delete"
            ]
          },
          {
            "OIDC": [
              "poi:subscriptions:delete"
            ]
          },
          {
            "DeviceID": []
          }
        ],
        "summary": "Deletes a previously created POI subscription\n"
      }
    },
    "/v1/tiles/query": {
      "post": {
        "tags": [
          "Tiles"
        ],
        "operationId": "GetTiles",
        "security": [
          {
            "OAuth2": [
              "poi:tiles:read"
            ]
          },
          {
            "OIDC": [
              "poi:tiles:read"
            ]
          }
        ],
        "summary": "Query for tiles\n",
        "description": "Get a list of map tiles in the Protobuf binary wire format.\n"
      }
    },
    "/beta/sources": {
      "post": {
        "tags": [
          "Sources"
        ],
        "operationId": "CreateSource",
        "security": [
          {
            "OAuth2": [
              "poi:sources:create"
            ]
          },
          {
            "OIDC": [
              "poi:sources:create"
            ]
          }
        ],
        "summary": "Creates a new source",
        "description": "Creates a new source"
      },
      "get": {
        "tags": [
          "Sources"
        ],
        "operationId": "GetSources",
        "security": [
          {
            "OAuth2": [
              "poi:sources:read"
            ]
          },
          {
            "OIDC": [
              "poi:sources:read"
            ]
          }
        ],
        "summary": "Returns a paginated list of sources",
        "description": "Returns a paginated list of sources optionally filtered by poi type and/or name"
      }
    },
    "/beta/sources/{sourceId}": {
      "put": {
        "tags": [
          "Sources"
        ],
        "operationId": "UpdateSource",
        "security": [
          {
            "OAuth2": [
              "poi:sources:update"
            ]
          },
          {
            "OIDC": [
              "poi:sources:update"
            ]
          }
        ],
        "summary": "Updates source with specified id",
        "description": "Updates source with specified id"
      },
      "get": {
        "tags": [
          "Sources"
        ],
        "operationId": "GetSource",
        "security": [
          {
            "OAuth2": [
              "poi:sources:read"
            ]
          },
          {
            "OIDC": [
              "poi:sources:read"
            ]
          }
        ],
        "summary": "Returns source with specified id",
        "description": "Returns source with specified id"
      },
      "delete": {
        "tags": [
          "Sources"
        ],
        "operationId": "DeleteSource",
        "security": [
          {
            "OAuth2": [
              "poi:sources:delete"
            ]
          },
          {
            "OIDC": [
              "poi:sources:delete"
            ]
          }
        ],
        "summary": "Deletes source with specified id",
        "description": "Deletes source with specified id"
      }
    },
    "/beta/policies": {
      "get": {
        "tags": [
          "Policies"
        ],
        "operationId": "GetPolicies",
        "security": [
          {
            "OAuth2": [
              "poi:policies:read"
            ]
          },
          {
            "OIDC": [
              "poi:policies:read"
            ]
          }
        ],
        "summary": "Returns a paginated list of policies",
        "description": "Returns a paginated list of policies optionally filtered by poi type and/or country id and/or user id"
      },
      "post": {
        "tags": [
          "Policies"
        ],
        "operationId": "CreatePolicy",
        "security": [
          {
            "OAuth2": [
              "poi:policies:create"
            ]
          },
          {
            "OIDC": [
              "poi:policies:create"
            ]
          }
        ],
        "summary": "Creates a new policy",
        "description": "Creates a new policy"
      }
    },
    "/beta/policies/{policyId}": {
      "get": {
        "tags": [
          "Policies"
        ],
        "operationId": "GetPolicy",
        "security": [
          {
            "OAuth2": [
              "poi:policies:read"
            ]
          },
          {
            "OIDC": [
              "poi:policies:read"
            ]
          }
        ],
        "summary": "Returns policy with specified id",
        "description": "Returns policy with specified id"
      }
    },
    "/beta/events": {
      "get": {
        "tags": [
          "Events"
        ],
        "operationId": "GetEvents",
        "security": [
          {
            "OAuth2": [
              "poi:events:read"
            ]
          },
          {
            "OIDC": [
              "poi:events:read"
            ]
          }
        ],
        "summary": "Returns a list of events",
        "description": "Returns a list of events optionally filtered by poi type and/or country id and/or user id"
      }
    },
    "/beta/pois": {
      "get": {
        "tags": [
          "POI"
        ],
        "operationId": "GetPois",
        "security": [
          {
            "OAuth2": [
              "poi:pois:read",
              "poi:pois.references:read"
            ]
          },
          {
            "OIDC": [
              "poi:pois:read",
              "poi:pois.references:read"
            ]
          }
        ],
        "summary": "Returns a paginated list of POIs",
        "description": "Returns a paginated list of POIs optionally filtered by type, appId and/or query"
      }
    },
    "/beta/pois/{poiId}": {
      "get": {
        "tags": [
          "POI"
        ],
        "operationId": "GetPoi",
        "security": [
          {
            "OAuth2": [
              "poi:pois:read",
              "poi:pois.references:read"
            ]
          },
          {
            "OIDC": [
              "poi:pois:read",
              "poi:pois.references:read"
            ]
          }
        ],
        "summary": "Returns POI with specified id",
        "description": "Returns POI with specified id"
      },
      "patch": {
        "tags": [
          "POI"
        ],
        "operationId": "ChangePoi",
        "security": [
          {
            "OAuth2": [
              "poi:pois:update"
            ]
          },
          {
            "OIDC": [
              "poi:pois:update"
            ]
          }
        ],
        "summary": "Updates POI with specified id (only passed attributes will be updated)",
        "description": "Returns POI with specified id (only passed attributes will be updated)"
      }
    },
    "/beta/apps/query": {
      "get": {
        "tags": [
          "Apps"
        ],
        "operationId": "CheckForPaceApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:read"
            ]
          },
          {
            "OIDC": [
              "poi:apps:read"
            ]
          }
        ],
        "summary": "Query for location-based apps\n",
        "description": "These location-based PACE apps deliver additional services for PACE customers based on their current position.\nYou can (or should) trigger this whenever:\n* A longer stand-still is detected\n* The engine is turned off\n* Every 5 seconds if the user \"left the road\"\n\nPlease note that calling this API is very cheap and can be done regularly.\n"
      }
    },
    "/beta/apps": {
      "get": {
        "tags": [
          "Apps"
        ],
        "operationId": "GetApps",
        "security": [
          {
            "OAuth2": [
              "poi:apps:read"
            ]
          },
          {
            "OIDC": [
              "poi:apps:read"
            ]
          }
        ],
        "summary": "Returns a paginated list of apps",
        "description": "Returns a paginated list of apps optionally filtered by type and/or query.\n"
      },
      "post": {
        "tags": [
          "Apps"
        ],
        "operationId": "CreateApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:create"
            ]
          },
          {
            "OIDC": [
              "poi:apps:create"
            ]
          }
        ],
        "summary": "Creates a new application",
        "description": "Creates a new application"
      }
    },
    "/beta/apps/{appID}": {
      "get": {
        "tags": [
          "Apps"
        ],
        "operationId": "GetApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:read"
            ]
          },
          {
            "OIDC": [
              "poi:apps:read"
            ]
          }
        ],
        "summary": "Returns App with specified id",
        "description": "Returns App with specified id.\nIn case the query returns a `404` (`Not Found`) the app was deleted and should be deleted from any caches.\n"
      },
      "put": {
        "tags": [
          "Apps"
        ],
        "operationId": "UpdateApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:update"
            ]
          },
          {
            "OIDC": [
              "poi:apps:update"
            ]
          }
        ],
        "summary": "Updates App with specified id",
        "description": "Updates App with specified id"
      },
      "delete": {
        "tags": [
          "Apps"
        ],
        "operationId": "DeleteApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:delete"
            ]
          },
          {
            "OIDC": [
              "poi:apps:delete"
            ]
          }
        ],
        "summary": "Deletes App with specified id",
        "description": "Deletes App with specified id"
      }
    },
    "/beta/apps/{appID}/relationships/pois": {
      "get": {
        "tags": [
          "Apps"
        ],
        "operationId": "GetAppPOIsRelationships",
        "security": [
          {
            "OAuth2": [
              "poi:apps:read"
            ]
          },
          {
            "OIDC": [
              "poi:apps:read"
            ]
          }
        ],
        "summary": "Returns all POI relations for specified app id",
        "description": "Returns all POI relations for specified app id"
      },
      "patch": {
        "tags": [
          "Apps"
        ],
        "operationId": "UpdateAppPOIsRelationships",
        "security": [
          {
            "OAuth2": [
              "poi:apps:update"
            ]
          },
          {
            "OIDC": [
              "poi:apps:update"
            ]
          }
        ],
        "summary": "Update all POI relations for specified app id",
        "description": "Update all POI relations for specified app id"
      }
    },
    "/beta/datadumps/pois": {
      "get": {
        "tags": [
          "Data Dumps"
        ],
        "operationId": "GetPoisDump",
        "security": [
          {
            "OAuth2": [
              "poi:dumps:pois"
            ]
          },
          {
            "OIDC": [
              "poi:dumps:pois"
            ]
          }
        ],
        "summary": "Create a full POI dump\n",
        "description": "Dump all POI data in XLSX format, along with full amenities.\n"
      }
    },
    "/beta/datadumps/duplicatemap/{countryCode}": {
      "get": {
        "tags": [
          "Data Dumps"
        ],
        "operationId": "GetDuplicatesKML",
        "security": [
          {
            "OAuth2": [
              "poi:dumps:duplicatemap"
            ]
          },
          {
            "OIDC": [
              "poi:dumps:duplicatemap"
            ]
          }
        ],
        "summary": "Duplicate Map for country (KML)",
        "description": "Generates a map of potential gas station duplicates (closer than 50m to eachother) for specified country."
      }
    },
    "/beta/delivery/gas-stations/{gasStationId}/reference-status/{reference}": {
      "put": {
        "tags": [
          "Delivery"
        ],
        "operationId": "PutGasStationReferenceStatus",
        "security": [
          {
            "OAuth2": [
              "poi:gas-stations.references:update"
            ]
          },
          {
            "OIDC": [
              "poi:gas-stations.references:update"
            ]
          }
        ],
        "summary": "Creates or updates a reference status of a gas station",
        "description": "Creates or updates a reference status of a gas station"
      },
      "delete": {
        "tags": [
          "Delivery"
        ],
        "operationId": "DeleteGasStationReferenceStatus",
        "security": [
          {
            "OAuth2": [
              "poi:gas-stations.references:update"
            ]
          },
          {
            "OIDC": [
              "poi:gas-stations.references:update"
            ]
          }
        ],
        "summary": "Deletes a reference status of a gas station",
        "description": "Deletes a reference status of a gas station"
      }
    },
    "/beta/prices/regional": {
      "get": {
        "tags": [
          "Prices"
        ],
        "operationId": "GetRegionalPrices",
        "summary": "Search for regional prices in the area",
        "description": "Search for regional prices in the area centered at input latitude/longitude. Lower/Upper limits are set for each fuel type returned.\n"
      }
    },
    "/beta/admin/poi/dedupe": {
      "patch": {
        "tags": [
          "Admin"
        ],
        "operationId": "DeduplicatePoi",
        "security": [
          {
            "OAuth2": [
              "poi:pois:update"
            ]
          },
          {
            "OIDC": [
              "poi:pois:update"
            ]
          }
        ],
        "summary": "Specify if a list of POI are considered to be duplicates of a specific POI"
      }
    },
    "/beta/admin/poi/move": {
      "patch": {
        "tags": [
          "Admin"
        ],
        "operationId": "MovePoiAtPosition",
        "security": [
          {
            "OAuth2": [
              "poi:pois:update"
            ]
          },
          {
            "OIDC": [
              "poi:pois:update"
            ]
          }
        ],
        "summary": "Allows an admin to move a POI identified by its ID to a specific position"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OIDC": {
        "type": "openIdConnect",
        "openIdConnectUrl": "https://id.pace.cloud/auth/realms/pace/.well-known/openid-configuration"
      },
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://id.pace.cloud/auth/realms/pace/protocol/openid-connect/auth",
            "tokenUrl": "https://id.pace.cloud/auth/realms/pace/protocol/openid-connect/token",
            "refreshUrl": "https://id.pace.cloud/auth/realms/pace/protocol/openid-connect/token",
            "scopes": {
              "poi:apps:create": "Create an app",
              "poi:apps:delete": "Delete an app",
              "poi:apps:read": "Get/search for an app",
              "poi:apps:update": "Change an app",
              "poi:events:read": "Get/search for events",
              "poi:gas-stations:read": "Get/search for gas stations",
              "poi:gas-stations.references:read": "Enabled additional reference data on the gas station",
              "poi:gas-stations.references:update": "Write additional reference data on the gas station",
              "poi:pois:read": "Get/search for pois",
              "poi:pois.references:read": "Enabled additional reference data on the poi",
              "poi:pois:update": "Update a poi",
              "poi:policies:create": "Create a policy",
              "poi:policies:read": "Get/search for policies",
              "poi:sources:create": "Create a source",
              "poi:sources:delete": "Delete a source",
              "poi:sources:read": "Get/search for sources",
              "poi:sources:update": "Update a source",
              "poi:subscriptions:read": "List all subscriptions",
              "poi:subscriptions:create": "Create a subscription",
              "poi:subscriptions:delete": "Delete a subscription",
              "poi:tiles:read": "Get/search for tiles"
            }
          }
        }
      },
      "DeviceID": {
        "type": "apiKey",
        "in": "header",
        "name": "Device-ID",
        "description": "Authentication using a unique device id. This is allows usage of the api without a user account. The device id has to be 32 bytes long and is best generated with a secure random function. E.g. `3b5cb427432aee46a2aa1dbad6f1c7629ec7928ce732afdd73ff7554b9c46272` generated using `openssl rand -hex 32`. The device id may not be the same across a re-install of the app. In case the device id is lost, all data stored with that device id is lost. If a device ID is not seen for a l[...]"
      }
    }
  }
}
