{
  "openapi": "3.0.0",
  "info": {
    "title": "PACE POI API",
    "description": "POI API",
    "version": "0.0.1",
    "x-logo": {
      "url": "https://developer.pace.car/images/logo_black.svg"
    }
  },
  "servers": [
    {
      "url": "https://api.pace.cloud/poi"
    }
  ],
  "paths": {
    "/beta/gas-stations": {
      "get": {
        "tags": [
          "Gas Stations"
        ],
        "operationId": "GetGasStations",
        "security": [
          {
            "OAuth2": [
              "poi:gas-stations:read"
            ]
          }
        ],
        "summary": "Query for gas stations",
        "description": "There are three possibilities to search for gas stations. If you want to search in a specific radius around a given longitude and latitude you have to provide the following query parameters:\n\n* latitude (required)\n* longitude (required)\n* radius (required)\n* accuracy (optional)\n\nIf you want to search in a given bounding box you have to provide the following query parameters:\n\n* boundingBox (required)\n\nIf you want to search along a given path you have to provide[...]"
      }
    },
    "/beta/gas-stations/{id}": {
      "get": {
        "tags": [
          "Gas Stations"
        ],
        "operationId": "GetGasStation",
        "security": [
          {
            "OAuth2": [
              "poi:gas-stations:read"
            ]
          }
        ],
        "summary": "Get a specific gas station",
        "description": "Returns an individual gas station\n"
      }
    },
    "/beta/subscriptions": {
      "post": {
        "tags": [
          "Subscriptions"
        ],
        "operationId": "CreateSubscription",
        "security": [
          {
            "OAuth2": [
              "poi:subscriptions:create"
            ]
          }
        ],
        "summary": "Create a POI subscription\n",
        "description": "Create a POI subscription to send a push notification to the device with the specified `pushToken` once you enter the specified `area`, which is currently described by a polygon. If you specify `types`, you only get one of those POI types in the push notification. The notification contains (max 4kb)\n\n```\n{\n  \"target\": \"mapkit\"\n  \"poi\": {\n    \"id\": \"B064797C-C644-4D48-8DDD-E2D6A7D86770\", # poi ID\n    \"type\": \"movableCamera\",\n    \"attributes\": {\n   [...]"
      }
    },
    "/beta/tiles/query": {
      "post": {
        "tags": [
          "Tiles"
        ],
        "operationId": "GetTiles",
        "security": [
          {
            "OAuth2": [
              "poi:tiles:read"
            ]
          }
        ],
        "summary": "Query for tiles\n",
        "description": "Get a list of map tiles in the Protobuf binary wire format.\n"
      }
    },
    "/beta/sources": {
      "post": {
        "tags": [
          "Sources"
        ],
        "operationId": "CreateSource",
        "security": [
          {
            "OAuth2": [
              "poi:sources:create"
            ]
          }
        ],
        "summary": "Creates a new source",
        "description": "Creates a new source"
      },
      "get": {
        "tags": [
          "Sources"
        ],
        "operationId": "GetSources",
        "security": [
          {
            "OAuth2": [
              "poi:sources:read"
            ]
          }
        ],
        "summary": "Returns a paginated list of sources",
        "description": "Returns a paginated list of sources optionally filtered by poi type and/or name"
      }
    },
    "/beta/sources/{sourceId}": {
      "put": {
        "tags": [
          "Sources"
        ],
        "operationId": "UpdateSource",
        "security": [
          {
            "OAuth2": [
              "poi:sources:update"
            ]
          }
        ],
        "summary": "Updates source with specified id",
        "description": "Updates source with specified id"
      },
      "get": {
        "tags": [
          "Sources"
        ],
        "operationId": "GetSource",
        "security": [
          {
            "OAuth2": [
              "poi:sources:read"
            ]
          }
        ],
        "summary": "Returns source with specified id",
        "description": "Returns source with specified id"
      },
      "delete": {
        "tags": [
          "Sources"
        ],
        "operationId": "DeleteSource",
        "security": [
          {
            "OAuth2": [
              "poi:sources:delete"
            ]
          }
        ],
        "summary": "Deletes source with specified id",
        "description": "Deletes source with specified id"
      }
    },
    "/beta/policies": {
      "get": {
        "tags": [
          "Policies"
        ],
        "operationId": "GetPolicies",
        "security": [
          {
            "OAuth2": [
              "poi:policies:read"
            ]
          }
        ],
        "summary": "Returns a paginated list of policies",
        "description": "Returns a paginated list of policies optionally filtered by poi type and/or country id and/or user id"
      },
      "post": {
        "tags": [
          "Policies"
        ],
        "operationId": "CreatePolicy",
        "security": [
          {
            "OAuth2": [
              "poi:policies:create"
            ]
          }
        ],
        "summary": "Creates a new policy",
        "description": "Creates a new policy"
      }
    },
    "/beta/policies/{policyId}": {
      "get": {
        "tags": [
          "Policies"
        ],
        "operationId": "GetPolicy",
        "security": [
          {
            "OAuth2": [
              "poi:policies:read"
            ]
          }
        ],
        "summary": "Returns policy with specified id",
        "description": "Returns policy with specified id"
      }
    },
    "/beta/events": {
      "get": {
        "tags": [
          "Events"
        ],
        "operationId": "GetEvents",
        "security": [
          {
            "OAuth2": [
              "poi:events:read"
            ]
          }
        ],
        "summary": "Returns a list of events",
        "description": "Returns a list of eventsoptionally filtered by poi type and/or country id and/or user id"
      }
    },
    "/beta/pois": {
      "get": {
        "tags": [
          "POI"
        ],
        "operationId": "GetPois",
        "security": [
          {
            "OAuth2": [
              "poi:pois:read"
            ]
          }
        ],
        "summary": "Returns a paginated list of POIs",
        "description": "Returns a paginated list of POIs optionally filtered by type, appId and/or query"
      }
    },
    "/beta/pois/{poiId}": {
      "get": {
        "tags": [
          "POI"
        ],
        "operationId": "GetPoi",
        "security": [
          {
            "OAuth2": [
              "poi:pois:read"
            ]
          }
        ],
        "summary": "Returns POI with specified id",
        "description": "Returns POI with specified id"
      },
      "patch": {
        "tags": [
          "POI"
        ],
        "operationId": "ChangePoi",
        "security": [
          {
            "OAuth2": [
              "poi:pois:update"
            ]
          }
        ],
        "summary": "Updates POI with specified id (only passed attributes will be updated)",
        "description": "Returns POI with specified id (only passed attributes will be updated)"
      }
    },
    "/beta/apps/query": {
      "get": {
        "tags": [
          "Apps"
        ],
        "operationId": "CheckForPaceApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:read"
            ]
          }
        ],
        "summary": "Query for location-based apps\n",
        "description": "These location-based PACE apps deliver additional services for PACE customers based on their current position.\nYou can (or should) trigger this whenever:\n* A longer stand-still is detected\n* The engine is turned off\n* Every 5 seconds if the user \"left the road\"\n\nPlease note that calling this API is very cheap and can be done regularly.\n"
      }
    },
    "/beta/apps": {
      "get": {
        "tags": [
          "Apps"
        ],
        "operationId": "GetApps",
        "security": [
          {
            "OAuth2": [
              "poi:apps:read"
            ]
          }
        ],
        "summary": "Returns a paginated list of apps",
        "description": "Returns a paginated list of apps optionally filtered by type and/or query"
      },
      "post": {
        "tags": [
          "Apps"
        ],
        "operationId": "CreateApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:create"
            ]
          }
        ],
        "summary": "Creates a new application",
        "description": "Creates a new application"
      }
    },
    "/beta/apps/{appID}": {
      "get": {
        "tags": [
          "Apps"
        ],
        "operationId": "GetApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:read"
            ]
          }
        ],
        "summary": "Returns App with specified id",
        "description": "Returns App with specified id"
      },
      "put": {
        "tags": [
          "Apps"
        ],
        "operationId": "UpdateApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:update"
            ]
          }
        ],
        "summary": "Updates App with specified id",
        "description": "Updates App with specified id"
      },
      "delete": {
        "tags": [
          "Apps"
        ],
        "operationId": "DeleteApp",
        "security": [
          {
            "OAuth2": [
              "poi:apps:delete"
            ]
          }
        ],
        "summary": "Deletes App with specified id",
        "description": "Deletes App with specified id"
      }
    },
    "/beta/apps/{appID}/relationships/pois": {
      "get": {
        "tags": [
          "Apps"
        ],
        "operationId": "GetAppPOIsRelationships",
        "security": [
          {
            "OAuth2": [
              "poi:apps:read"
            ]
          }
        ],
        "summary": "Returns all POI relations for specified app id",
        "description": "Returns all POI relations for specified app id"
      },
      "patch": {
        "tags": [
          "Apps"
        ],
        "operationId": "UdpateAppPOIsRelationships",
        "security": [
          {
            "OAuth2": [
              "poi:apps:update"
            ]
          }
        ],
        "summary": "Update all POI relations for specified app id",
        "description": "Update all POI relations for specified app id"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://id.pace.cloud/oauth2/authorize",
            "tokenUrl": "https://id.pace.cloud/oauth2/token",
            "refreshUrl": "https://id.pace.cloud/oauth2/token",
            "scopes": {
              "poi:apps:create": "Create an app",
              "poi:apps:delete": "Delete an app",
              "poi:apps:read": "Get/search for an app",
              "poi:apps:update": "Change an app",
              "poi:events:read": "Get/search for events",
              "poi:gas-stations:read": "Get/search for gas stations",
              "poi:pois:read": "Get/search for pois",
              "poi:pois:update": "Update a poi",
              "poi:policies:create": "Create a policy",
              "poi:policies:read": "Get/search for policies",
              "poi:sources:create": "Create a source",
              "poi:sources:delete": "Delete a source",
              "poi:sources:read": "Get/search for sources",
              "poi:sources:update": "Update a source",
              "poi:subscriptions:create": "Create a subscription",
              "poi:tiles:read": "Get/search for tiles"
            }
          }
        }
      }
    }
  }
}