// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: tools/testserver/math/math.proto

package math

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_tools_testserver_math_math_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_tools_testserver_math_math_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_tools_testserver_math_math_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Input) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             int64                  `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_tools_testserver_math_math_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_tools_testserver_math_math_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_tools_testserver_math_math_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

var File_tools_testserver_math_math_proto protoreflect.FileDescriptor

var file_tools_testserver_math_math_proto_rawDesc = []byte{
	0x0a, 0x20, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x4d, 0x61, 0x74, 0x68, 0x22, 0x23, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x61, 0x12,
	0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x62, 0x22, 0x16, 0x0a,
	0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x01, 0x63, 0x32, 0x56, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x68, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0b, 0x2e, 0x4d, 0x61,
	0x74, 0x68, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0c, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0x2e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x12, 0x0b, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x0c, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x17, 0x5a,
	0x15, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tools_testserver_math_math_proto_rawDescOnce sync.Once
	file_tools_testserver_math_math_proto_rawDescData = file_tools_testserver_math_math_proto_rawDesc
)

func file_tools_testserver_math_math_proto_rawDescGZIP() []byte {
	file_tools_testserver_math_math_proto_rawDescOnce.Do(func() {
		file_tools_testserver_math_math_proto_rawDescData = protoimpl.X.CompressGZIP(file_tools_testserver_math_math_proto_rawDescData)
	})
	return file_tools_testserver_math_math_proto_rawDescData
}

var file_tools_testserver_math_math_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tools_testserver_math_math_proto_goTypes = []any{
	(*Input)(nil),  // 0: Math.Input
	(*Output)(nil), // 1: Math.Output
}
var file_tools_testserver_math_math_proto_depIdxs = []int32{
	0, // 0: Math.MathService.Add:input_type -> Math.Input
	0, // 1: Math.MathService.Subtract:input_type -> Math.Input
	1, // 2: Math.MathService.Add:output_type -> Math.Output
	1, // 3: Math.MathService.Subtract:output_type -> Math.Output
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tools_testserver_math_math_proto_init() }
func file_tools_testserver_math_math_proto_init() {
	if File_tools_testserver_math_math_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tools_testserver_math_math_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tools_testserver_math_math_proto_goTypes,
		DependencyIndexes: file_tools_testserver_math_math_proto_depIdxs,
		MessageInfos:      file_tools_testserver_math_math_proto_msgTypes,
	}.Build()
	File_tools_testserver_math_math_proto = out.File
	file_tools_testserver_math_math_proto_rawDesc = nil
	file_tools_testserver_math_math_proto_goTypes = nil
	file_tools_testserver_math_math_proto_depIdxs = nil
}
